language: cpp
os:
  - osx
compiler:
  - clang
before_install:
  - brew update
  - brew install cryptopp libatomic_ops
script: ./configure --with-debug --without-fuse --without-libaio
branches:
  only:
    - master
    - /^port.*$/
